export const SET_BOARD = 'SET_BOARD';
export const SET_TAGS = 'SET_TAGS'
export const SET_SELECTED_TAGS = 'SET_SELECTED_TAGS'
export const SET_EXERCIESES = 'SET_EXERCIESES'
export const LOADING_BOARD = 'LOADING_BOARD'